// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khaswjnemdzgvwqiybqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoYXN3am5lbWR6Z3Z3cWl5YnF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTQ3NDIsImV4cCI6MjA2NTgzMDc0Mn0.RbDTwkrPxhQjkukgqFTjTeJhCiIRvQJgzVJ1p9ny2O0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);